<%@ Page Title="" Language="C#" MasterPageFile="~/Interface.Master" AutoEventWireup="true" CodeBehind="AcademicInfo.aspx.cs" Inherits="VirtualCampus.AcademicInfo" %>
<asp:Content ID="Content1" ContentPlaceHolderID="InterfacetitlePlaceHolder" runat="server">
Student Academic Information
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .style14
        {
            color: #3399FF;
        }
        .style15
        {
            font-weight: bold;
            color: #CC33FF;
        }
        .style16
        {
            width: 167px;
        }
        .style17
        {
            width: 260px;
        }
        .style18
        {
            width: 127px;
        }
        .style19
        {
            text-align: right;
            width: 402px;
        }
        .style20
        {
            color: #0000FF;
        }
        .style21
        {
            color: #FF00FF;
        }
        .style22
        {
            width: 307px;
        }
        .style23
        {
            color: #FF3300;
            background-color: #FFFF66;
        }
        .style24
        {
            color: #000000;
            width: 1350px;
            text-align: left;
            height: 596px;
            margin: 10px auto;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <table class="style6">
        <tr>
            <td class="style12">
                <strong>
                <br />
                <asp:Label ID="Label2" runat="server" CssClass="style24" 
                    Text="Academic Information Search"></asp:Label>
                <br />
                <br />
                </strong>
            </td>
        </tr>
    </table>
    <table class="style6">
        <tr>
            <td class="style19">
                <strong>
                <asp:Label ID="Label3" runat="server" Text="Enter Student_id :"></asp:Label>
                </strong>
            </td>
            <td class="style18">
                <strong>
                <asp:TextBox ID="txtSearchBox" runat="server" BorderStyle="Ridge" 
                    CssClass="style15"></asp:TextBox>
                </strong>
            </td>
            <td class="style17">
                <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
                    Text="Display Academic Information" />
            </td>
            <td class="style16">
                <strong>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                    ControlToValidate="txtSearchBox" ErrorMessage="Please Enter Student_id!" 
                    ForeColor="Red">Student_id Must Be Provided!</asp:RequiredFieldValidator>
                </strong>
            </td>
            <td>
                <strong>
                <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" 
                    ControlToValidate="txtSearchBox" ErrorMessage="Only Numbers Are Allowed!" 
                    ForeColor="#006600" ValidationExpression="\d{0,9}"></asp:RegularExpressionValidator>
                </strong>
            </td>
        </tr>
    </table>
    <table class="style6">
        <tr>
            <td class="style12">
                <strong>
                <asp:Label ID="lblWhatHappened" runat="server" CssClass="style21"></asp:Label>
                </strong>
            </td>
        </tr>
    </table>
    <table class="style6">
        <tr>
            <td class="style12">
                <strong>
                <asp:Label ID="lblHeader" runat="server" CssClass="style20"></asp:Label>
                </strong>
            </td>
        </tr>
    </table>
    <table class="style6">
        <tr>
            <td class="style22">
                <strong>
                <asp:ValidationSummary ID="ValidationSummary1" runat="server" 
                    CssClass="style23" 
                    HeaderText="Errors List(Generated By Abraham's Intellient System)" 
                    ShowMessageBox="True" />
                </strong>
            </td>
            <td>
                <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" 
                    AutoGenerateRows="False" DataKeyNames="Student_id" 
                    DataSourceID="SqlDataSource1" Height="61px" Width="485px">
                    <Fields>
                        <asp:BoundField DataField="Student_id" HeaderText="Student_id" 
                            InsertVisible="False" ReadOnly="True" SortExpression="Student_id" />
                        <asp:BoundField DataField="CollegeName" HeaderText="CollegeName" 
                            SortExpression="CollegeName" />
                        <asp:BoundField DataField="CollegeAddress" HeaderText="CollegeAddress" 
                            SortExpression="CollegeAddress" />
                        <asp:BoundField DataField="PCourse" HeaderText="PCourse" 
                            SortExpression="PCourse" />
                        <asp:BoundField DataField="PYearPassed" HeaderText="PYearPassed" 
                            SortExpression="PYearPassed" />
                        <asp:BoundField DataField="Promo" HeaderText="Promo" SortExpression="Promo" />
                        <asp:BoundField DataField="Course" HeaderText="Course" 
                            SortExpression="Course" />
                        <asp:BoundField DataField="DateOfAdmission" HeaderText="DateOfAdmission" 
                            SortExpression="DateOfAdmission" />
                        <asp:BoundField DataField="Semester" HeaderText="Semester" 
                            SortExpression="Semester" />
                        <asp:BoundField DataField="Section" HeaderText="Section" 
                            SortExpression="Section" />
                        <asp:BoundField DataField="RollNo" HeaderText="RollNo" 
                            SortExpression="RollNo" />
                    </Fields>
                </asp:DetailsView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:MyConnectionString %>" 
                    SelectCommand="SELECT Student_id, CollegeName, CollegeAddress, PCourse, PYearPassed, Promo, Course, DateOfAdmission, Semester, Section, RollNo FROM StudentRegistrations WHERE Student_id=@Student_id">
                    <SelectParameters>
                        <asp:ControlParameter ControlID="txtSearchBox" Name="Student_id" 
                            PropertyName="Text" />
                    </SelectParameters>
                </asp:SqlDataSource>
            </td>
            <td>
                &nbsp;</td>
        </tr>
    </table>
</asp:Content>
